services:

  jenkins:

    build:
      context: .
      dockerfile: Dockerfile

    image: jenkins-devops:2.0

    container_name: jenkins-ctn

    restart: unless-stopped

    ports:
      - "8080:8080"
      - "50000:50000"

    environment:
      HOME: /var/jenkins_home
      KUBECONFIG: /var/jenkins_home/.kube/config

    group_add:
      - "984"

    volumes:
      - jenkins-vol:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock

      - /home/gabriel/.kube:/var/jenkins_home/.kube:ro
      - /home/gabriel/.minikube:/var/jenkins_home/.minikube:ro


volumes:

  jenkins-vol: