services:
  jenkins:

    image: jenkins-devops:2.0

    container_name: jenkins-ctn

    restart: unless-stopped

    ports:
      - "8080:8080"
      - "50000:50000"

    environment:
      HOME: /var/jenkins_home
      KUBECONFIG: /home/gabriel/.kube/config
      MINIKUBE_HOME: /home/gabriel/.minikube

    volumes:

      - jenkins-vol:/var/jenkins_home

      - /var/run/docker.sock:/var/run/docker.sock

      - /home/gabriel/.kube:/home/gabriel/.kube:ro

      - /home/gabriel/.minikube:/home/gabriel/.minikube:ro

    group_add:
      - "984"

    networks:
      - minikube

volumes:
  jenkins-vol:

networks:
  minikube:
    external: true