apiVersion: apps/v1
kind: Deployment

metadata:
  name: fivexo
  namespace: fivexo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: fivexo

  template:
    metadata:
      labels:
        app: fivexo

    spec:
      containers:
        - name: fivexo

          image: 5xo:latest
          imagePullPolicy: Never

          ports:
            - containerPort: 5000

          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 2

          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 2

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"