apiVersion: apps/v1
kind: Deployment

metadata:
  name: 5xo
  namespace: 5xo

spec:
  replicas: 1

  selector:
    matchLabels:
      app: 5xo

  template:

    metadata:
      labels:
        app: 5xo

    spec:

      containers:

      - name: 5xo

        image: gabrieldinu987/5xo:latest

        imagePullPolicy: Always

        ports:

        - containerPort: 5000

        readinessProbe:

          httpGet:
            path: /
            port: 5000

          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 2
          failureThreshold: 3

        livenessProbe:

          httpGet:
            path: /
            port: 5000

          initialDelaySeconds: 20
          periodSeconds: 10
          timeoutSeconds: 2
          failureThreshold: 3

        resources:

          requests:
            cpu: "100m"
            memory: "128Mi"

          limits:
            cpu: "500m"
            memory: "512Mi"