apiVersion: v1
kind: Service

metadata:
  name: 5xo-service
  namespace: 5xo

spec:

  selector:
    app: 5xo

  type: NodePort

  ports:

  - protocol: TCP

    port: 5000

    targetPort: 5000

    nodePort: 30080